media: src/assets/images
content:  
  - name: artigos
    label: Artigos
    type: collection
    path: src/content/docs
    filename: "{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descrição
        type: string
      - name: sidebar
        label: Configuração da Sidebar
        type: object
        fields:
          - name: order
            label: Ordem no Menu
            type: number
      - name: body
        label: Conteúdo do Artigo
        type: rich-text
  - name: publicar
    label: 🚀 Publicar Oficial
    type: file
    path: publicar.json
    fields:
      - name: publicar_agora
        label: Ativar Publicação
        type: boolean
        description: "Marque esta caixa e clique em 'Save'. O robô irá atualizar o site oficial com todo o conteúdo atual do Preview. A chave voltará para 'falso' automaticamente depois de alguns segundos."