media: src/assets/images
content:
  - name: artigos
    label: Artigos
    type: collection
    path: src/content/docs
    format: yaml-frontmatter
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descrição
        type: string
      - name: sidebar
        label: Configuração da Sidebar
        type: object
        fields:
          - name: order
            label: Ordem no Menu
            type: number
      - name: body
        label: Conteúdo do Artigo
        type: rich-text