name: Notificação do Preview

# Agora escutamos os "Checks" dos commits quando eles terminam
on:
  check_run:
    types: [completed]

jobs:
  notificar_discord:
    runs-on: ubuntu-latest
    # A Mágica: Só roda se o aviso vier do aplicativo da Cloudflare E se for na branch preview
    if: github.event.check_run.app.name == 'Cloudflare Pages' && github.event.check_run.check_suite.head_branch == 'preview'
    
    steps:
      - name: Enviar Sucesso para o Discord
        if: github.event.check_run.conclusion == 'success'
        run: |          
          curl -H "Content-Type: application/json" \
          -d '{"content": "✅ **Preview Atualizado!**\nAs alterações foram compiladas e estão prontas para revisão."}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Enviar Falha para o Discord
        if: github.event.check_run.conclusion == 'failure' || github.event.check_run.conclusion == 'timed_out'
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "❌ **Erro no deploy do Preview!**\n"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
